import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/header";
import { Footer } from "@/components/footer/footer";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" />
      </head>
      <body className={inter.className}>
        
        {/* agar koi component aapne website kay har */}
        {/* page m dikhaa h to use hame */}
        {/* layout.js m rakhna cahhyie */}
      <Header></Header>

        {/* yahan pages changes horehte jab */}
        {/* bhi user kisi link per click krta */}
        <main>
          {children}
        </main>

      <Footer></Footer>

      <ToastContainer></ToastContainer>

        </body>
    </html>
  );
}
